apiVersion: v1
kind: Namespace
metadata:
  name: ehealth
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: ehealth
type: Opaque
stringData:
  POSTGRES_USER: "healthcare_admin"
  POSTGRES_PASSWORD: "SuperSecurePassword2026"
  POSTGRES_DB: "patients_db"
